### PR TITLE
Format long strings

### PR DESCRIPTION
**Pull request by eduardosm**
rustfmt does not format strings by default and may prevent whole blocks from being formatted.

Long strings (and blocks containing them) have been formatted with:
```
cargo fmt -- --config format_strings=true
```

### CODE REVIEW

**Comment by fabianschuiki** [comment]
Or, coming to think of it, we could also add a `.rustfmt.toml` file with this option. This way we don't need to change commands and have a place for future non-standard config options. What do you think?

**Comment by eduardosm** [comment]
Using that option in `.rustfmt.toml` will print
```
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
```
(with the option being ignored)

So I'm not sure how much a good idea it is enabling the option permanently enabling the option. I have done a pass with just `cargo fmt` to fix the differences found in Travis. In most cases, long strings that were formatted with `format_strings=true` will not be affected.

For now, I suggest to use unstable features only when needed (e.g., some block is not being correctly formatted).

**Comment by fabianschuiki** [comment]
I see, so I guess you are using a nightly toolchain on your system, where the option is available? I fully agree with you that we should stick to stable rust, which also precludes the use of these options in the CI. But going over the code with a nightly build, and then doing a regular `cargo fmt` to sync up with what Travis expects should be sufficient.

If you quickly rebase onto master to resolve the conflicts (or re-run the command on a fresh master) I can merge :+1:

**Comment by eduardosm** [comment]
Rebased

**Comment by fabianschuiki** [comment]
Awesome, thanks! I'll merge as soon as the checks pass.

**Pull request merged**
